# Generated by Django 6.0.7 on 2026-08-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-version_number']},
        ),
        migrations.AddField(
            model_name='resume',
            name='version_number',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together={('student', 'version_number')},
        ),
    ]
