# Generated by Django 6.0.7 on 2026-08-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
