# Generated by Django 6.0.7 on 2026-08-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hr_name', models.CharField(blank=True, max_length=255)),
                ('hr_email', models.EmailField(blank=True, max_length=254)),
                ('hr_contact', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_type', models.CharField(blank=True, choices=[('SERVICE', 'Service'), ('PRODUCT', 'Product'), ('STARTUP', 'Startup'), ('GOVERNMENT', 'Government')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('locations', models.TextField(blank=True, help_text='Comma-separated list of office locations')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
