# Generated by Django 6.0.7 on 2026-08-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True)),
                ('package_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('minimum_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('eligible_branch', models.CharField(blank=True, help_text='E.g., CSE, ISE, ECE or All', max_length=255)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('drive_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='companies.company')),
            ],
        ),
    ]
