# Generated by Django 6.0.7 on 2026-08-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_drive', '0002_alter_placementdrive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required technical skills'),
        ),
    ]
